modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="realmfinder"
version="1.1.0"
displayName="RealmFinder"
authors="HyIsNoob"
description='''Capture a slice of Minecraft and make the photograph become reality elsewhere.'''

[[dependencies.realmfinder]]
modId="neoforge"
type="required"
versionRange="[21.1.251,)"
ordering="NONE"
side="BOTH"

[[dependencies.realmfinder]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="realmfinder.client.mixins.json"
